# Permalinks
permalink:        /:year-:month-:day-:title.html
relative_permalinks: true

# Setup
title:            James Wilson
tagline:          Web developer. Drupal enthusiast. Surfer and musician. I craft bespoke websites at <a href="http://bluespark.com">Bluespark</a>.
url:              http://jameswilson.github.io
paginate:         3
markdown:         redcarpet
baseurl:          /
author:
  name:           James
  url:            https://twitter.com/jwilson3
  email:          jrwilson3@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jameswilson/jameswilson.github.io

# Main navigation (see _layouts/default.html for usage)
pages_list:
  About: '/about.html'
  Twitter: 'http://twitter.com/jwilson3'
  Archive: '/archive.html'
  Feed: '/atom.xml'
