# Github Pages preferences (do not change)
github:           [metadata]
highlighter:      rouge

# Repository configuration
repository:       jameswilson/jameswilson.github.io
version:          2.0.0

# Jekyll site configuration
title:            James Wilson
tagline:          Open Source Technologist &amp; Senior Web Developer
description: >-   # Used in homepage metatag and RSS feed description.
  The personal blog of James Wilson; senior frontend web developer and Open
  Source enthusiast.
url:              http://jameswilson.github.io
baseurl:          ""  # change to /subdir if the site is located in a subfolder
permalink:        /:year-:month-:day-:title.html
paginate:         3

# Calculate post reading time based on number of words.
# A floating point number is required for the divide_by calcuation.
words_per_minute: 180.0

# Post excerpts
# Remove or comment out the following line tells Jekyll to use the first
# paragraph of each post as the excerpt.
excerpt_separator: <!--more-->

# Disqus comment configuration.
# See _include/comments.html for usage.
disqus:
  enabled:        false
  shortname:      jwilson3-postach-io

# Main navigation links.
# See _includes/navigation.html for usage.
navigation:
  - title: Blog
    url: /
  - title: Archive
    url: /archive
  - title: About
    url: /about
  - title: Search
    url: /search

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
