# Github Pages preferences (do not change)
github:           [metadata]
highlighter:      rouge

# Enable the following Github Pages optional Plugins
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap

# Repository configuration
repository:       jameswilson/jameswilson.github.io
version:          2.2.0

# Jekyll site configuration
title:            James Wilson
title_separator:  "&middot;"
tagline:          Open Source Technologist &amp; Senior Web Developer
description: >-   # Used in homepage metatag and RSS feed description.
                  The personal blog of James Wilson; senior web developer
                  at Bluespark and avid Open Source enthusiast.
url:              https://jameswilson.github.io
baseurl:          # the subpath of your site, e.g. "/blog"
permalink:        /:year-:month-:day-:title
paginate:         3

# og:image metatag default (override this per post/page in post's front matter)
image:            https://i.imgur.com/UNe5t4v.jpg

analytics:
  enabled:        true
  tracking_id:    UA-45354089-1

google:
  search_engine_id: 005468932483752946890:jvbt67gzrjm

# Global author
author:
  name:           James
  twitter:        jwilson3
  url:            https://twitter.com/jwilson3
  email:          jrwilson3@gmail.com
  image:          https://i.imgur.com/aXOJjYr.png

# Calculate post reading time based on number of words.
# A floating point number is required for the divide_by calcuation.
words_per_minute: 180.0

# Post excerpts
# Remove or comment out the following line tells Jekyll to use the first
# paragraph of each post as the excerpt.
excerpt_separator: <!--more-->

# Disqus comment configuration.
# See _include/comments.html for usage.
disqus:
  enabled:        true
  shortname:      jameswilson-blog

# Jekyll Feed plugin options
feed:
  path: atom.xml  # override the default /feed.xml

# Main navigation links.
# See _includes/navigation.html for usage.
navigation:
  - title: Blog
    url: /
  - title: Archives
    url: /archives
  - title: About
    url: /about
  - title: Search
    url: /search

# Process pages in the following additional custom subfolders.
# Note these pages must use the 'permalink' parameter in yaml front matter
# in order for Jekyll to place them correctly into the site's url structure.
include:
  - _pages
  - _redirect

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
