# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://jameswilson.github.io/
paginate:         1
baseurl:          /
author:
  name:           James Wilson
  url:            https://twitter.com/jwilson3
  email:          jrwilson3@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
