# Permalinks
permalink:        /:year-:month-:day-:title.html

# Setup
title:            James Wilson
tagline:          Open Source Technologist &amp; Senior Web Developer
description: >-
  The personal blog of James Wilson; senior frontend web developer and Open
  Source enthusiast.
url:              http://jameswilson.github.io
paginate:         3
markdown:         redcarpet
highlighter:      pygments
baseurl:          ""
author:
  name:           James
  url:            https://twitter.com/jwilson3
  email:          jrwilson3@gmail.com

# Reading time, this must be a float for divide_by to work.
words_per_minute: 180.0

excerpt_separator: <!--more-->

# Disqus config
disqus:
  enabled:        false
  shortname:      jwilson3-postach-io

# Custom vars
version:          2.0.0
github:           [metadata]
repository:       jameswilson/jameswilson.github.io

# Main navigation links (see _includes/navigation.html for usage)
navigation:
  - title: Blog
    url: /
  - title: Archive
    url: /archive
  - title: About
    url: /about
  - title: Search
    url: /search

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
